baseURL = 'https://adamstruve.com/'
languageCode = 'en-us'
title = 'Adam Struve'
theme = 'anatole'


[params]
title = "Adam Struve"
author = "Adam Struve"
description = "Web Developer"
profilePicture = "images/adamstruve.jpg"
mainSections = []
doNotLoadAnimations = true

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/adamstruve/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/adamstruve"

[[params.socialIcons]]
icon = "fab fa-facebook"
title = "Facebook"
url = "https://www.facebook.com/adamstruve"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/adamstruve/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/adamstruve"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:adam@adamstruve.com"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Resume"
  weight = 200
  identifier = "resume"
  url = "/resume/"

  [[menu.main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/projects/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

copyright = "2020-{{ YEAR }}"